STAMP_PRESETS = {
    "clean": {
        "effects": {
            "ink_color": (125, 88, 170),
            "opacity_min": 0.78,
            "opacity_max": 0.95,
            "visibility_mode": "uniform",
            "char_dropout_prob": 0.0,
            "word_dropout_prob": 0.0,
            "section_dropout_prob": 0.0,
            "missing_ink_prob": 0.0,
            "blur_radius_min": 0.0,
            "blur_radius_max": 0.2,
            "rotation_min": -1.0,
            "rotation_max": 1.0,
            "ghost_prob": 0.0,
            "washed_out_prob": 0.0,
            "edge_fade_prob": 0.0,
            "crop_prob": 0.0,
            "scan_noise_prob": 0.0,
            "jpeg_artifact_prob": 0.0,
        },
    },
    "light_faded": {
        "effects": {
            "ink_color": (115, 80, 165),
            "opacity_min": 0.45,
            "opacity_max": 0.78,
            "visibility_mode": "per_word",
            "char_dropout_prob": 0.04,
            "word_dropout_prob": 0.08,
            "missing_ink_prob": 0.25,
            "missing_ink_strength": 0.3,
            "blur_radius_min": 0.2,
            "blur_radius_max": 0.8,
            "rotation_min": -3.0,
            "rotation_max": 3.0,
            "ghost_prob": 0.05,
            "washed_out_prob": 0.1,
            "scan_noise_prob": 0.1,
        },
    },
    "medical_faded": {
        "effects": {
            "ink_color": (108, 73, 166),
            "opacity_min": 0.28,
            "opacity_max": 0.72,
            "visibility_mode": "per_character",
            "char_dropout_prob": 0.12,
            "word_dropout_prob": 0.06,
            "section_dropout_prob": 0.18,
            "missing_ink_prob": 0.45,
            "missing_ink_strength": 0.52,
            "blur_radius_min": 0.7,
            "blur_radius_max": 1.4,
            "rotation_min": -4.0,
            "rotation_max": 4.0,
            "ghost_prob": 0.18,
            "washed_out_prob": 0.35,
            "edge_fade_prob": 0.30,
            "crop_prob": 0.15,
            "scan_noise_prob": 0.2,
            "jpeg_artifact_prob": 0.12,
        },
    },
    "medical_uneven_ink": {
        "effects": {
            "ink_color": (105, 68, 160),
            "opacity_min": 0.25,
            "opacity_max": 0.78,
            "visibility_mode": "per_section",
            "char_dropout_prob": 0.08,
            "section_dropout_prob": 0.25,
            "missing_ink_prob": 0.55,
            "missing_ink_strength": 0.6,
            "blur_radius_min": 0.4,
            "blur_radius_max": 1.1,
            "rotation_min": -4.5,
            "rotation_max": 4.5,
            "ghost_prob": 0.12,
            "washed_out_prob": 0.2,
            "edge_fade_prob": 0.35,
        },
    },
    "medical_with_black_signature": {
        "effects": {
            "ink_color": (104, 68, 168),
            "opacity_min": 0.30,
            "opacity_max": 0.80,
            "visibility_mode": "per_character",
            "char_dropout_prob": 0.08,
            "section_dropout_prob": 0.16,
            "missing_ink_prob": 0.42,
            "missing_ink_strength": 0.48,
            "blur_radius_min": 0.6,
            "blur_radius_max": 1.2,
            "rotation_min": -5.0,
            "rotation_max": 5.0,
            "strong_rotation_prob": 0.2,
            "strong_rotation_min": -12.0,
            "strong_rotation_max": 12.0,
            "ghost_prob": 0.2,
            "washed_out_prob": 0.22,
            "edge_fade_prob": 0.3,
            "crop_prob": 0.2,
            "scan_noise_prob": 0.25,
            "jpeg_artifact_prob": 0.16,
        },
        "handwriting": {
            "enabled": True,
            "mode": "signature",
            "overlap_prob": 1.0,
            "text_prob": 0.2,
            "signature_prob": 0.8,
            "opacity_min": 0.82,
            "opacity_max": 0.98,
            "line_width_min": 2,
            "line_width_max": 4,
        },
    },
    "medical_with_black_handwriting": {
        "effects": {
            "ink_color": (110, 72, 168),
            "opacity_min": 0.30,
            "opacity_max": 0.72,
            "visibility_mode": "per_word",
            "char_dropout_prob": 0.09,
            "section_dropout_prob": 0.12,
            "missing_ink_prob": 0.3,
            "blur_radius_min": 0.5,
            "blur_radius_max": 1.0,
            "rotation_min": -4.0,
            "rotation_max": 4.0,
            "ghost_prob": 0.1,
            "washed_out_prob": 0.2,
        },
        "handwriting": {
            "enabled": True,
            "mode": "text",
            "overlap_prob": 1.0,
            "text_prob": 0.9,
            "signature_prob": 0.1,
        },
    },
    "medical_ghosted": {
        "effects": {
            "ink_color": (106, 71, 165),
            "opacity_min": 0.32,
            "opacity_max": 0.74,
            "visibility_mode": "per_character",
            "char_dropout_prob": 0.08,
            "ghost_prob": 0.45,
            "ghost_opacity_min": 0.18,
            "ghost_opacity_max": 0.35,
            "ghost_offset_min": 2,
            "ghost_offset_max": 12,
            "blur_radius_min": 0.5,
            "blur_radius_max": 1.2,
        },
    },
    "medical_washed_out": {
        "effects": {
            "ink_color": (112, 79, 168),
            "opacity_min": 0.22,
            "opacity_max": 0.62,
            "visibility_mode": "per_section",
            "char_dropout_prob": 0.1,
            "missing_ink_prob": 0.55,
            "missing_ink_strength": 0.65,
            "blur_radius_min": 1.1,
            "blur_radius_max": 2.0,
            "washed_out_prob": 0.6,
            "washed_out_strength_min": 0.35,
            "washed_out_strength_max": 0.65,
            "edge_fade_prob": 0.45,
        },
    },
    "medical_extreme_scan": {
        "effects": {
            "ink_color": (98, 64, 152),
            "opacity_min": 0.18,
            "opacity_max": 0.58,
            "visibility_mode": "per_character",
            "char_dropout_prob": 0.16,
            "word_dropout_prob": 0.12,
            "section_dropout_prob": 0.2,
            "missing_ink_prob": 0.65,
            "missing_ink_strength": 0.72,
            "blur_radius_min": 0.9,
            "blur_radius_max": 2.2,
            "rotation_min": -6.0,
            "rotation_max": 6.0,
            "ghost_prob": 0.28,
            "washed_out_prob": 0.5,
            "edge_fade_prob": 0.4,
            "crop_prob": 0.35,
            "scan_noise_prob": 0.8,
            "jpeg_artifact_prob": 0.65,
        },
        "handwriting": {
            "enabled": True,
            "mode": "text_or_signature",
            "overlap_prob": 0.85,
        },
    },
}
